/**
 * @fileoverview TypeScript type definitions for Apps Script namespace: MimeType.
 * This file was autogenerated by the Apps Script SDK.
 */


  export enum MimeType {
    BMP,
    CSS,
    CSV,
    FOLDER,
    GIF,
    GOOGLE_APPS_SCRIPT,
    GOOGLE_DOCS,
    GOOGLE_DRAWINGS,
    GOOGLE_FORMS,
    GOOGLE_SHEETS,
    GOOGLE_SLIDES,
    HTML,
    JAVASCRIPT,
    JPEG,
    MICROSOFT_EXCEL,
    MICROSOFT_EXCEL_LEGACY,
    MICROSOFT_POWERPOINT,
    MICROSOFT_POWERPOINT_LEGACY,
    MICROSOFT_WORD,
    MICROSOFT_WORD_LEGACY,
    OPENDOCUMENT_GRAPHICS,
    OPENDOCUMENT_PRESENTATION,
    OPENDOCUMENT_SPREADSHEET,
    OPENDOCUMENT_TEXT,
    PDF,
    PLAIN_TEXT,
    PNG,
    RTF,
    SVG,
    ZIP
  }

