/**
 * @fileoverview TypeScript type definitions for Apps Script namespace: Logger.
 * This file was autogenerated by the Apps Script SDK.
 */


declare class Logger {
  static clear(): void;
  static getLog(): string;
  static log(data: any): Logger;
  static log(format: string, ...values: any[]): Logger;
}

