/**
 * @fileoverview TypeScript type definitions for Apps Script namespace: CacheService.
 * This file was autogenerated by the Apps Script SDK.
 */


declare class CacheService {
  static getDocumentCache(): CacheService.Cache;
  static getScriptCache(): CacheService.Cache;
  static getUserCache(): CacheService.Cache;
}

declare namespace CacheService {

  export interface Cache {

    get(key: string): string;
    getAll(keys: string[]): any;
    put(key: string, value: string): void;
    put(key: string, value: string, expirationInSeconds: number): void;
    putAll(values: any): void;
    putAll(values: any, expirationInSeconds: number): void;
    remove(key: string): void;
    removeAll(keys: string[]): void;

  }


}