/**
 * @fileoverview TypeScript type definitions for Apps Script namespace: ContentService.
 * This file was autogenerated by the Apps Script SDK.
 */


declare class ContentService {
  static createTextOutput(): ContentService.TextOutput;
  static createTextOutput(content: string): ContentService.TextOutput;
}

declare namespace ContentService {

  export enum MimeType {

    ATOM,
    CSV,
    ICAL,
    JAVASCRIPT,
    JSON,
    RSS,
    TEXT,
    VCARD,
    XML

  }


  export interface TextOutput {

    append(addedContent: string): ContentService.TextOutput;
    clear(): ContentService.TextOutput;
    downloadAsFile(filename: string): ContentService.TextOutput;
    getContent(): string;
    getFileName(): string;
    getMimeType(): ContentService.MimeType;
    setContent(content: string): ContentService.TextOutput;
    setMimeType(mimeType: ContentService.MimeType): ContentService.TextOutput;

  }


}