/**
 * @fileoverview TypeScript type definitions for Apps Script namespace: Browser.
 * This file was autogenerated by the Apps Script SDK.
 */


declare class Browser {
  static inputBox(prompt: string): string;
  static inputBox(prompt: string, buttons: CommonModule.ButtonSet): string;
  static inputBox(title: string, prompt: string, buttons: CommonModule.ButtonSet): string;
  static msgBox(prompt: string): string;
  static msgBox(prompt: string, buttons: CommonModule.ButtonSet): string;
  static msgBox(title: string, prompt: string, buttons: CommonModule.ButtonSet): string;
}

