/**
 * @fileoverview TypeScript type definitions for Apps Script namespace: LockService.
 * This file was autogenerated by the Apps Script SDK.
 */


declare class LockService {
  static getDocumentLock(): LockService.Lock;
  static getScriptLock(): LockService.Lock;
  static getUserLock(): LockService.Lock;
}

declare namespace LockService {

  export interface Lock {

    hasLock(): boolean;
    releaseLock(): void;
    tryLock(timeoutInMillis: number): boolean;
    waitLock(timeoutInMillis: number): void;

  }


}