/**
 * @fileoverview TypeScript type definitions for Apps Script namespace: LanguageApp.
 * This file was autogenerated by the Apps Script SDK.
 */


declare class LanguageApp {
  static translate(text: string, sourceLanguage: string, targetLanguage: string): string;
  static translate(text: string, sourceLanguage: string, targetLanguage: string, advancedArgs: any): string;
}

