/**
 * @fileoverview TypeScript type definitions for Apps Script namespace: DebugApp.
 * This file was autogenerated by the Apps Script SDK.
 */


declare class DebugApp {
  static applyFunctionInMainProject(functionName: string, args: any[]): any;
  static busyLoop(): void;
  static getBuildData(): any;
  static getCallingLibId(): string;
  static getExecutionEnvironment(): string;
  static getInvocationType(): string;
  static getParamInfo(x: any): string;
  static identity(x: any): any;
  static interruptibleBusyLoop(): void;
  static loadBrix(): void;
  static sleepWithContinuation(milliseconds: number): void;
  static throwContinuation(): void;
  static throwRuntimeException(message: string): void;
  static throwUserException(): void;
}

